### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dotnize** [dotnize/sveltor#1]
Initial example

- [ ] Modular components
  - [ ] Component list
  - [ ] Canvas
  - [ ] Property editor
  - [ ] Outline
- [ ] Fields/properties
  - [ ] Load external data
- [ ] Initial json data structure for output
  - [ ] allow programmatic changes to the data?
- [ ] <Render />

future ideas

- [ ] component categories
- [ ] dynamic props & fields
- [ ] load external data
- [ ] iframe support for dynamic viewport previews
